#!/bin/bash

# change to directory where videos are stored - TODO: Change this
cd /Users/Mitali/Desktop/IndividualProject/fmp/FilmAudioProgram/video/videos

# strip audio from video file and return this
ffmpeg -i input.mp4 -an -vcodec copy output.mp4

# wait 10 secs for any errors on terminal
sleep 10